### ISSUE TITLE
Request for addition of scroll keyword in testx library

### ISSUE THREAD

**Issue by abhinaveonics** [testxio/testx#13]
Can I reqeust you to please add the scroll keyword in testx library for the following 

Step 1. When I try to register I get the following screen

![image](https://user-images.githubusercontent.com/36408845/36097325-ce491eb2-0ffa-11e8-9316-d2c326a73631.png)

Step 2: When I click on the the link "I have read and accept the Terms and Conditions" I get the following screen where I need to scroll down till bottom to accept the terms and condition

![image](https://user-images.githubusercontent.com/36408845/36097291-a7c0b57a-0ffa-11e8-84f5-06fe5679bd5a.png)

**Comment by bruindav** [comment]
Maybe you can use the send keys  keyword to scoll down ??

send keys Send key strokes to focussed element, supporting specials keys,
such as [TAB] and [ENTER]. Supported key strokes can be found here:
http://selenium.googlecode.com/git/docs/api/javascript/enum_webdriver_Key.html

2018-02-12 13:44 GMT+01:00 abhinaveonics <notifications@github.com>:

**Comment by greyarch** [comment]
@abhinaveonics Is there any way for me to test a possible solution? Do you expose this web site/app publicly somewhere?
You can create a custom keyword yourself which does something like:
```
browser.executeScript('arguments[0].scrollIntoView()', testx.element(elementKey).getWebElement());
```

**Comment by abhinaveonics** [comment]
https://portal.uturn-system.com/register

and please select carrier or shipper to get the terms and conditions link.

**Comment by greyarch** [comment]
@abhinaveonics There is no need for additional keyword. TestX will just go to the element you want to set. In your case you need to do this:
1. Define these objects (CSV format for conciseness):
```
carrier,css,"div.item.selectable.first"
terms,css,"div.tc-text"
scroll,css,"div.hidden-extra-scroll"
accept,xpath,"//button[contains(.,'accept')]"
```
2. Do this in your **testx** script:
```
- go to:
    url: /register
- set:
    carrier:
    terms:
    scroll:
    accept:
```
The trick here is to click on the **scroll** element, that is on the bottom of the screen.
Hope this helps.

**Comment by abhinaveonics** [comment]
Thanks. It works.
