### ISSUE TITLE
Installation in new directory gives jasmine related config errors

### ISSUE THREAD

**Issue by maneeshparihar** [testxio/testx#19]
Hi, when i install testx in a new directory by using npm install testx. It gives jasmine related configuration errors. When I start with testx-quickstart templates then it works fine. Request if you can look into it or update any other prerequisites.

**Comment by greyarch** [comment]
Hey, what exactly is the error you are getting?
The best way to create a new testx project is by globally installing [**@testx/cli**](https://github.com/testxio/testx-cli) and then doing
```bash
testx init
```
in your working directory.

Check out the [**@testx/cli**](https://github.com/testxio/testx-cli) project for more details.

**Comment by maneeshparihar** [comment]
Hi Greyarch,

Thanks for your revert. I was trying with the following npm module testx.

npm install testx --save

with this I was getting errors related to @testx/reporters-jasmine not
being installed and jasmine keyword not recognized (something on those
lines).

I will try with the testx/cli npm module provided by you and will get back
in case if I face an issue.

Thanks for your support and reply.

Maneesh Parihar
