### ISSUE TITLE
Assign sysdate to a field

### ISSUE THREAD

**Issue by BobSoeterbroek** [testxio/testx#23]
I've made the following statement in my testx-file:

- set:
    DateArrival: ${sysdate}

But it fails with the following error:

sysdate is not defined

Do I need a specific module/object to utilize this?

I have the following setup:

  onPrepare: ->
    require 'testx'
    testx.objects.add require './objects'
    testx.objects.add require 'testx-standard-objects'
    testx.keywords.add(require './keywords')

**Comment by greyarch** [comment]
Hey Bob,
  It fails like that because there is no *sysdate* function added to your context. You need to implement it yourself and add it to the test context with (in your conf file):

```testx.functions.add("path/to/function/impl")```

The function itself will be something to the tune of (in JS):
```
module.exports = {
  sysdate: function() {return new Date().toDateString()}
}
```

**Comment by BobSoeterbroek** [comment]
Thank you!
I've made a new folder called 'datefunction' on the same level as 'keywords' and 'objects'. Within I added an index.coffee with your suggested javascript function.

I added testx.functions.add('./datefunction') to my above mentioned setup in my conf file.

Still I get the error sysdate is not defined.
Do I miss something else here?

**Comment by BobSoeterbroek** [comment]
I added 'require' like this:
testx.functions.add(require './datefunction')

and now it finds the function but I can't use the reserved word 'function' in it.

**Comment by greyarch** [comment]
I see you are using CoffeeScript. The examples above are in JS.
For Coffee you'd do:

```
module.exports =
  sysdate: -> new Date().toDateString()
```

**Comment by BobSoeterbroek** [comment]
The function works now!
I'm using toLocaleDateString to try to get dd-mm-yyyy output.

Unfortunately the output is yyyy-mm-dd although my locale conventions are set to nl-NL. 
If I try to pass the argument myself it still gives the wrong output.

sysdate: -> new Date().toLocaleDateString('nl-NL')

I also checked if Chrome was using local conventions and it does.
Any idea?

**Comment by greyarch** [comment]
Providing the locale explicitly should work fine. Are you certain you do not need to transpile after the code change? Maybe you are still using the old code, the one without the locale setting?

**Comment by BobSoeterbroek** [comment]
Yes I'm certain unfortunately. When I pass 'en-US' it changes to mm-dd-yyyy.
I even tried countries with backwards notations to NL, but then it displays correctly for that country yyyy-mm-dd. 
Do you happen to know another way besides this method to get the current date and set the format?

Thanks for all your support!

**Comment by greyarch** [comment]
You can perhaps use [moment.js](https://momentjs.com/) to format any way you want.

**Comment by BobSoeterbroek** [comment]
Define a function like this:

moment = require "moment"

module.exports =

  sysdate: (dateformat) ->
    moment().format(dateformat)

In the script you call it like this:

- set:
     DateArrival:${sysdate('DD-MM-YYYY')}

**Comment by greyarch** [comment]
Excellent!
