### ISSUE TITLE
TestX scripts are failing in docker setup (used in CI/CD pipeline)

### ISSUE THREAD

**Issue by eonicslabs** [testxio/testx#26]
We are getting these errors on every run for all ARTs

1. Element is not clickable- other element will receive the click
2. Page deleted due to page crash
3. State reference element not found etc

In 80% of the scenarios it is the first error.

All the scripts run fine when running them normally using chrome window and "protractor conf.coffee" command without any issues but fail in docker setup.

It seems  that when we scroll using Sendkeys (TAB, PG DN, END etc), then it fails with error that element is not clickable. In normal run  the scroll and test case working absolutely fine without any issues.

url - https://acc.jigler.nl/
[Docker-issue.zip](https://github.com/testxio/testx/files/4254681/Docker-issue.zip)

**Comment by greyarch** [comment]
Which version of testx do you use?

**Comment by eonicslabs** [comment]
{
  "name": "testx-quickstart",
  "version": "4.0.0",
  "description": "Seed testx project.",
  "main": "conf.coffee",
  "author": "Gantcho Kojuharov <gantcho@greyarch.net> (http://greyarch.net)",
  "license": "ISC",
  "dependencies": {
    "coffee-script": "^1.12.7",
    "faker": "^4.1.0",
    "lodash": "^4.17.11",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "testx": "^2.11.0",
    "testx-file-keywords": "^0.3.0",
    "testx-html-reporter": "^0.1.0",
    "testx-jasmine-reporters": "^1.1.1",
    "testx-pdf-keywords": "^0.3.1",
    "testx-standard-objects": "^0.1.1"
  },
  "scripts": {
    "webdriver-update": "webdriver-manager update",
    "test": "docker run --rm -v $(pwd):/work --net=host testx/protractor conf.coffee",
    "test-local": "protractor conf.coffee",
    "apitest": "mocha"
  },
  "testx": {
    "logScript": false,
    "actionTimeout": 40000
  },
  "devDependencies": {
    "chakram": "^1.5.0",
    "protractor": "^5.4.1"
  }
}


But in pipeline run the testx image is pulled from hub.docker.com, testx/protractor

**Comment by eonicslabs** [comment]
This is the content of Dockerfile

FROM testx/protractor
WORKDIR /work/
COPY ./package*.json ./
RUN npm install

COPY ./ ./

**Comment by greyarch** [comment]
What version of node/npm do you use? I get **Failed: testx is not defined** right off the bat with this project. Furthermore, your *Docker-issue.zip* file does not contain *package.json*. I assume it is the one you pasted in your earlier response.
